# Generated by Django 5.2.1 on 2025-06-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_setup', '0002_tipounidadacademica_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ciclo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='academic_setup.unidadacademica'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='orden',
            field=models.IntegerField(help_text='Orden numérico para los ciclos (ej: 1, 2, 3...)'),
        ),
        migrations.AlterUniqueTogether(
            name='ciclo',
            unique_together={('carrera', 'orden')},
        ),
    ]
