# Generated by Django 5.2.1 on 2025-06-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_setup', '0003_alter_ciclo_unique_together_alter_carrera_unidad_and_more'),
        ('scheduling', '0002_grupos_ciclo_semestral'),
        ('users', '0002_alter_docentes_telefono'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariosasignados',
            unique_together={('docente', 'periodo', 'dia_semana', 'bloque_horario'), ('espacio', 'periodo', 'dia_semana', 'bloque_horario'), ('grupo', 'periodo', 'dia_semana', 'bloque_horario')},
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='materia',
        ),
        migrations.AddField(
            model_name='grupos',
            name='materias',
            field=models.ManyToManyField(related_name='grupos', to='academic_setup.materias'),
        ),
        migrations.AddField(
            model_name='horariosasignados',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases_impartidas', to='academic_setup.materias'),
        ),
        migrations.AlterUniqueTogether(
            name='horariosasignados',
            unique_together={('docente', 'periodo', 'dia_semana', 'bloque_horario'), ('espacio', 'periodo', 'dia_semana', 'bloque_horario'), ('grupo', 'materia', 'periodo'), ('grupo', 'periodo', 'dia_semana', 'bloque_horario')},
        ),
    ]
