# Generated by Django 5.2.1 on 2025-06-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_setup', '0003_alter_ciclo_unique_together_alter_carrera_unidad_and_more'),
        ('scheduling', '0003_alter_horariosasignados_unique_together_and_more'),
        ('users', '0002_alter_docentes_telefono'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariosasignados',
            unique_together={('docente', 'periodo', 'dia_semana', 'bloque_horario'), ('espacio', 'periodo', 'dia_semana', 'bloque_horario'), ('grupo', 'materia', 'periodo', 'dia_semana', 'bloque_horario'), ('grupo', 'periodo', 'dia_semana', 'bloque_horario')},
        ),
    ]
